### ISSUE TITLE
Compatibility with 9.5.6

### ISSUE THREAD

**Issue by enannos** [cconard96/glpi-webresources-plugin#22]
Hello,

is there a way that we can make the plugin compatible with the latest GLPI.

If I install it, it works but it creates a new menu "plugins" on top of the menu bar.

Thank you

**Comment by cconard96** [comment]
The new menu is expected behavior. It is a menu provided by GLPI itself that is meant to be used for plugins, but nobody seems to use it so it is almost always empty and therefore hidden.

The option to move the menu has existed for a while now and should show up under Setup > General on the Web Resources tab.
