### ISSUE TITLE
Enhancement Idea - Supplier websites

### ISSUE THREAD

**Issue by raregtp** [cconard96/glpi-webresources-plugin#7]
While updating some supplier info today, got to thinking that it would be really useful if the supplier websites on the Supplier's pages showed up as webresources automatically.  Perhaps a drop-down at the top that would let you pick between Supplier's websites, URL's from appliances (web appliances), ad-hoc, entities, etc.  Just thinking it would be nice to have a "central" area (Webresources) that brings together the URL's in each GLPI location into one central spot.

Dialog on this is welcome!!  Thanks!

**Comment by cconard96** [comment]
Does #8 meet these needs? See my comment there for a GIF of the feature.

**Comment by raregtp** [comment]
That's almost exactly like I imagined....thanks!!  I'll get this into our pre-prod environment ASAP, I appreciate it!

**Comment by cconard96** [comment]
Keep in mind that for appliances, it uses the original Web Applications plugin right now since it directly adds the URL and management URL fields.
Also, I'm going to merge this feature now but will be adding more to help organize these resources before an official release.
For suppliers and appliances it will likely be grouped by type.

**Comment by raregtp** [comment]
No worries…understand on the Web Applications plugin, and will keep tabs on the releases.  Appreciate it!

Matt


Matt Baker

Mobile: (402) 709-9933

matt@myacs.com<mailto:matt@myacs.com>

**Comment by cconard96** [comment]
A beta of the new version was just added to the GitHub releases. There are some performance considerations since the process of automatically fetching icons can take some time (and aren't 100% reliable). I added a lot of information into the release description on this. I will wait a few days in case anyone has feedback on this new version and in case there is anything else I can to do improve performance of the new dashboards.
